---
title: "Day6 Solution"
author: "Paul Kubat"
date: "12/23/2021"
output: html_document
---

```{r}
#Part 1
lanternfish <- c(3,5,2,5,4,3,2,2,3,5,2,3,2,2,2,2,3,5,3,5,5,2,2,3,4,2,3,5,5,3,3,5,2,4,5,4,3,5,3,2,5,4,1,1,1,5,1,4,1,4,3,5,2,3,2,2,2,5,2,1,2,2,2,2,3,4,5,2,5,4,1,3,1,5,5,5,3,5,3,1,5,4,2,5,3,3,5,5,5,3,2,2,1,1,3,2,1,2,2,4,3,4,1,3,4,1,2,2,4,1,3,1,4,3,3,1,2,3,1,3,4,1,1,2,5,1,2,1,2,4,1,3,2,1,1,2,4,3,5,1,3,2,1,3,2,3,4,5,5,4,1,3,4,1,2,3,5,2,3,5,2,1,1,5,5,4,4,4,5,3,3,2,5,4,4,1,5,1,5,5,5,2,2,1,2,4,5,1,2,1,4,5,4,2,4,3,2,5,2,2,1,4,3,5,4,2,1,1,5,1,4,5,1,2,5,5,1,4,1,1,4,5,2,5,3,1,4,5,2,1,3,1,3,3,5,5,1,4,1,3,2,2,3,5,4,3,2,5,1,1,1,2,2,5,3,4,2,1,3,2,5,3,2,2,3,5,2,1,4,5,4,4,5,5,3,3,5,4,5,5,4,3,5,3,5,3,1,3,2,2,1,4,4,5,2,2,4,2,1,4)

Days <- 0:8
countofFish <- c(0,tabulate(lanternfish, nbins = 8))
next_day <- rep(NA,9)
df <- data.frame(Days,countofFish,next_day)

for (d in 1:80) {
  num_reproducing <- df$countofFish[1]
  df$next_day[1:8] <- df$countofFish[2:9]
  df$next_day[7] <- df$next_day[7] + num_reproducing
  df$next_day[9] <- num_reproducing
  df$countofFish <- df$next_day
}

paste("There are" ,sum(df$countofFish), "lanternfish after 80 days!")
```

```{r}
#Part 2
Days <- 0:8
countofFish <- c(0,tabulate(lanternfish, nbins = 8))
next_day <- rep(NA,9)
df <- data.frame(Days,countofFish,next_day)

for (d in 1:256) {
  num_reproducing <- df$countofFish[1]
  df$next_day[1:8] <- df$countofFish[2:9]
  df$next_day[7] <- df$next_day[7] + num_reproducing
  df$next_day[9] <- num_reproducing
  df$countofFish <- df$next_day
}

paste("There are" ,sum(df$countofFish), "lanternfish after 256 days!")
```

